### ISSUE TITLE
Bug in time-range period text generation

### ISSUE THREAD

**Issue by wleightond** [geoltime/geoltime.github.io#2]
The range given for angiosperm radiation on wikipedia is [130-95 Ma](https://timescale.toolforge.org/?Ma=130%E2%80%9395). The text correctly says it's Phanerozoic, but also says it's Ectasian which is Proterozoic. 

Annotated screenshot:
![Screenshot would be here if it loads. Otherwise go to https://imgur.com/a/PiEZKtn](https://i.imgur.com/JNO0Iui.png)

**Comment by ms609** [comment]
Thanks for the report!  I suspect the issue arises because the en-dash is encoded with something that looks like `%10`, and the `10` runs into the `95` in one of the regular expression matches.

I've decided that the code underlying the timeline is ripe for some ... modernization.  I'm rewriting in Javascript, which will also make the code simpler to host and maintain in future.
